### ISSUE TITLE
Item glow stays for a second when you change creative tabs

### ISSUE THREAD

**Issue by slava110** [RealRTTV/malum-fabric#12]
Not really that big of an issue but if you can fix it would be great c:
![2022-06-19_08 07 25](https://user-images.githubusercontent.com/26705162/174466853-3a5911f4-b3a4-4cf6-962c-a0a7766d1e92.png)
![2022-06-19_08 08 23](https://user-images.githubusercontent.com/26705162/174466854-6616bb8a-49dd-4220-9efc-a0bde8f808d1.png)

**Comment by RealRTTV** [comment]
that's the... intent, tl;dr its called a screen particle and mimics how regular particles work but places it on the screen instead of in the world, this means (like normal particles) that they wont disappear immediately but fade after a few ticks, also the original malum mod does this with switching tabs and such

**Comment by slava110** [comment]
Okay. I just thought it is not okay to see this when switching between tabs. Sounds weird for me if it's intended...
